<?php

/**
 * ECM PDF Bootstrap
 *
 * Validates and creates tc-lib-pdf document instances.
 *
 * @package EventCertificateManager
 */

if (!defined('ABSPATH')) {
    exit;
}

class ECM_PDF_Bootstrap
{
    /**
     * Return ECM's runtime PDF font directory.
     *
     * This directory contains:
     * - ECM-generated custom PDF font assets.
     * - Copied tc-lib-pdf Core14 fallback font definitions.
     *
     * @return string
     */
    public static function get_fonts_directory()
    {
        if (!class_exists('ECM_Font_Manager')) {
            return '';
        }

        return ECM_Font_Manager::get_pdf_fonts_directory();
    }

    /**
     * Validate and prepare the tc-lib-pdf runtime environment.
     *
     * @return true|WP_Error
     */
    public static function validate()
    {
        /*
         * Confirm that the tc-lib-pdf library is available.
         */
        if (!class_exists('\Com\Tecnick\Pdf\Tcpdf')) {
            return new WP_Error(
                'ecm_pdf_library_missing',
                'tc-lib-pdf is not installed or Composer was not loaded.'
            );
        }

        /*
         * Prepare ECM's runtime PDF font directory.
         *
         * This copies the required Core14 fallback definitions
         * and preserves any ECM-generated custom font assets.
         */
        if (class_exists('ECM_PDF_Font_Manager')) {
            $prepared =
                ECM_PDF_Font_Manager::initialize_runtime_fonts();

            if (is_wp_error($prepared)) {
                return $prepared;
            }
        }

        /*
         * Confirm that the runtime font directory exists.
         */
        $fonts_directory = self::get_fonts_directory();

        if (
            !$fonts_directory ||
            !is_dir($fonts_directory)
        ) {
            return new WP_Error(
                'ecm_pdf_fonts_missing',
                'The ECM runtime PDF fonts directory is missing.'
            );
        }

        /*
         * Confirm that tc-lib-pdf can read the font directory.
         */
        if (!is_readable($fonts_directory)) {
            return new WP_Error(
                'ecm_pdf_fonts_unreadable',
                'The ECM runtime PDF fonts directory is not readable.'
            );
        }

        return true;
    }

    /**
     * Create a configured tc-lib-pdf document.
     *
     * @return \Com\Tecnick\Pdf\Tcpdf|WP_Error
     */
    public static function create_document()
    {
        /*
         * Validate tc-lib-pdf and prepare runtime font assets.
         */
        $validation = self::validate();

        if (is_wp_error($validation)) {
            return $validation;
        }

        /*
         * Resolve ECM's runtime PDF font directory.
         */
        $fonts_directory = realpath(
            self::get_fonts_directory()
        );

        if (!$fonts_directory) {
            return new WP_Error(
                'ecm_pdf_fonts_path_invalid',
                'The ECM runtime PDF fonts path could not be resolved.'
            );
        }

        /*
         * tc-lib-pdf reads prepared font definitions from
         * the K_PATH_FONTS directory.
         *
         * Define it only once because PHP constants cannot
         * be redefined during the same request.
         */
        if (!defined('K_PATH_FONTS')) {
            define(
                'K_PATH_FONTS',
                $fonts_directory
            );
        }

        try {
            /*
             * Create the PDF document.
             *
             * tc-lib-pdf defaults to millimetres, which ECM's
             * certificate renderers currently use.
             */
            $pdf = new \Com\Tecnick\Pdf\Tcpdf();

            /*
             * Configure document metadata.
             */
            $pdf->setCreator(
                'Event Certificate Manager'
            );

            $pdf->setAuthor(
                wp_strip_all_tags(
                    get_bloginfo('name')
                )
            );

            $pdf->setTitle(
                'ECM Certificate'
            );

            $pdf->setSubject(
                'Certificate generated by Event Certificate Manager'
            );

            $pdf->setKeywords(
                'ECM, certificate, PDF, tc-lib-pdf'
            );

            $pdf->setPDFFilename(
                'ecm-certificate.pdf'
            );

            return $pdf;

        } catch (Throwable $exception) {
            return new WP_Error(
                'ecm_pdf_initialization_failed',
                $exception->getMessage()
            );
        }
    }
}